# Generated by Django 3.1.5 on 2021-02-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='computers',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='notebooks',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='printers',
        ),
    ]
